# Generated by Django 2.0.4 on 2018-04-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Complain',
        ),
    ]
