# Generated by Django 2.0.4 on 2018-04-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_auto_20180418_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='further_comments',
            new_name='further_complain',
        ),
        migrations.AlterField(
            model_name='complain',
            name='university_address',
            field=models.TextField(max_length=400),
        ),
    ]
